version: "2"

services:
  grafana:
    image: grafana/grafana:5.1.0
    ports:
      - "${GRAFANA_PORT}:3000"
    volumes:
      - grafana-vol:/data/db
    network_mode: host
    restart: "${RESTART}"

volumes:
  grafana-vol:
    driver: local
