version: "2"

services:
  grafana:
    image: grafana/grafana:v7.0.0-beta3
    ports:
      - "${GRAFANA_PORT}:3000"
    volumes:
      - grafana-vol:/data/db
    network_mode: bridge
    restart: "${RESTART}"

volumes:
  grafana-vol:
    driver: local
